import { Assistant } from "next/font/google";
import "./globals.css";
import { ToastContainer, toast } from 'react-toastify';
import GlobalProvider from "@/components/Application/GlobalProvider";
const AssistantFont = Assistant({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${AssistantFont.className} antialiased`}
      >
        <GlobalProvider>
          <ToastContainer />
          {children}
        </GlobalProvider>

      </body>
    </html>
  );
}
